### PR TITLE
Docker: Fix `kubectl` download and update Alpine.

### PR DESCRIPTION
**Pull request by Gacko**

### CODE REVIEW

**Comment by AverageMarcus** [comment]
Looks like we're missing an entry in retagger:
```
ERROR: failed to solve: quay.io/giantswarm/alpine:3.20: failed to resolve source metadata for quay.io/giantswarm/alpine:3.20: quay.io/giantswarm/alpine:3.20: not found
```

**Comment by Gacko** [comment]
... or maybe we only copy it to Azure CR?

**Comment by Gacko** [comment]
https://github.com/giantswarm/retagger/blob/01ff723edf200f94539afe07c03bfa771b3fe0e4/images/skopeo-docker-io.yaml#L167

We need to specify the patch, I guess.

**Comment by AverageMarcus** [comment]
Good catch! :D

**Review by AverageMarcus — APPROVED** [review]

**Comment by AverageMarcus** [comment]
Fixes: https://github.com/giantswarm/giantswarm/issues/31773

**Comment by Gacko** [comment]
Guess we also need to re-release the latest tags then.

**Comment by Gacko** [comment]
Ah, nevermind. There is a v1.31.2 out, so "something" will bump the version in the next hours/days anyway.

**Pull request merged**
